export const RouterConstantUtil = {
  routes: {
    auth: {
      login: "/auth/login",
      // baseRegisterRoute: "/auth/register",
      registrationPhases: "/auth/register/:phase",
      firstPhaseRegister: "/auth/register/user",
      secondPhaseRegister: "/auth/register/info",
      baseCompleteKyc: "/auth/completeKyc",
      completeKyc: "/auth/completeKyc/:id",
      // successful: "/auth/successful",
      baseAcountVerification: "/auth/verifyYourAccount",
      verifyUserAccount: "/auth/verifyYourAccount/:id",
      forgetPassword: "/auth/forgetPassword",
      completeForgetPassword: "/auth/completeForgetPassword",
      changeNewPassword: "/auth/changeNewPassword",
    },
    page: {
      baseEmailVerificationSuccessful: "/emailVerificationSuccessful",
      emailVerificationSuccessful: "/emailVerificationSuccessful/:token",
      registrationCompleted: "/registrationCompleted",
      basePasswordReset: "/resetPassword",
      passwordReset: "/resetPassword/:token",
      passwordResetEmailSent: "/resetEmailSent",
      passwordResetSuccessful: "/resetPasswordSuccess",
      overview: "/page/overview",
      noPageFound: "/page/noPageFound",
      home: "/page/home",
      searchResult: "/page/property/search-result",
      bookmark: "/page/bookmark",
      basePropertyDetails: "/page/property/details",
      propertyDetails: "/page/property/details/:id",
      agentProfile: "/page/agent/profile",
      referrals: "/page/referrals",
    },
  },
};
